package net.mcreator.tbm.init;

import net.mcreator.tbm.item.APartOfSimulatedCommandBlockItem;
import net.mcreator.tbm.item.AmiriItem;
import net.mcreator.tbm.item.BlockGoldItem;
import net.mcreator.tbm.item.HhhItem;
import net.mcreator.tbm.item.HjItem;
import net.mcreator.tbm.item.HunterGunItem;
import net.mcreator.tbm.item.ItemOfTheQueenMutantItem;
import net.mcreator.tbm.item.JjjItem;
import net.mcreator.tbm.item.LavaItem;
import net.mcreator.tbm.item.LkItem;
import net.mcreator.tbm.item.MItem;
import net.mcreator.tbm.item.MbbItem;
import net.mcreator.tbm.item.MeddsItem;
import net.mcreator.tbm.item.Mgri2Item;
import net.mcreator.tbm.item.MgriItem;
import net.mcreator.tbm.item.MngwItem;
import net.mcreator.tbm.item.MsbItem;
import net.mcreator.tbm.item.MsbuItem;
import net.mcreator.tbm.item.MysteriousPotionItem;
import net.mcreator.tbm.item.Rocket2Item;
import net.mcreator.tbm.item.SlamItem;
import net.mcreator.tbm.item.SuperSkullItem;
import net.mcreator.tbm.item.SuperSonicBoomItem;
import net.mcreator.tbm.item.Sw2Item;
import net.mcreator.tbm.item.SwItem;
import net.mcreator.tbm.item.TdItem;
import net.mcreator.tbm.item.TrfhItem;
import net.mcreator.tbm.item.VgItem;
import net.mcreator.tbm.item.WomwItem;
import net.minecraft.world.item.Item;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ThemutantmobsmodModItems {
   public static final DeferredRegister<Item> REGISTRY;
   public static final RegistryObject<Item> MUTANT_ZOMBIFIED_PIGLIN_SPAWN_EGG;
   public static final RegistryObject<Item> MUTANT_IRON_GOLEM_SPAWN_EGG;
   public static final RegistryObject<Item> MUTANT_DROWNED_SPAWN_EGG;
   public static final RegistryObject<Item> MUTANT_RAVAGER_SPAWN_EGG;
   public static final RegistryObject<Item> MUTANT_WARDEN_SPAWN_EGG;
   public static final RegistryObject<Item> GOLDS_SPAWN_EGG;
   public static final RegistryObject<Item> BLOCK_GOLD;
   public static final RegistryObject<Item> TD;
   public static final RegistryObject<Item> MUTANT_ZOMBIE_VILLAGER_SPAWN_EGG;
   public static final RegistryObject<Item> MUTANT_ZOGLIN_SPAWN_EGG;
   public static final RegistryObject<Item> MUTANT_DROWNED_1_SPAWN_EGG;
   public static final RegistryObject<Item> MUTANT_DROWNED_2_SPAWN_EGG;
   public static final RegistryObject<Item> MUTANT_DROWNED_3_SPAWN_EGG;
   public static final RegistryObject<Item> HUNTER_GUN;
   public static final RegistryObject<Item> SUPER_SONIC_BOOM;
   public static final RegistryObject<Item> MUTANT_WITHER_SPAWN_EGG;
   public static final RegistryObject<Item> SUPER_SKULL;
   public static final RegistryObject<Item> LAVA;
   public static final RegistryObject<Item> MUTANT_STRIDER_SPAWN_EGG;
   public static final RegistryObject<Item> GIGAILLAGER_SPAWN_EGG;
   public static final RegistryObject<Item> JJJ;
   public static final RegistryObject<Item> HHH;
   public static final RegistryObject<Item> GIGAILLAGER_V_2_SPAWN_EGG;
   public static final RegistryObject<Item> MUTANTENDERDRAGON_SPAWN_EGG;
   public static final RegistryObject<Item> MAGICMADEBYMUTANTENDERDRAGON_SPAWN_EGG;
   public static final RegistryObject<Item> MEDDS;
   public static final RegistryObject<Item> MUTANTSTRAY_SPAWN_EGG;
   public static final RegistryObject<Item> MSB;
   public static final RegistryObject<Item> MSBU;
   public static final RegistryObject<Item> MUTANT_NETHERITE_GOLEM_SPAWN_EGG;
   public static final RegistryObject<Item> MNGW;
   public static final RegistryObject<Item> SLAM;
   public static final RegistryObject<Item> MUTANT_SNIFFER_SPAWN_EGG;
   public static final RegistryObject<Item> ANCIENT_TREE_SPAWN_EGG;
   public static final RegistryObject<Item> TRFH;
   public static final RegistryObject<Item> MUTANT_GHAST_SPAWN_EGG;
   public static final RegistryObject<Item> MGRI;
   public static final RegistryObject<Item> MMBMG_SPAWN_EGG;
   public static final RegistryObject<Item> MGRI_2;
   public static final RegistryObject<Item> ALPHA_MUTANT_IRON_GOLEM_SPAWN_EGG;
   public static final RegistryObject<Item> AMIRI;
   public static final RegistryObject<Item> TRYU_SPAWN_EGG;
   public static final RegistryObject<Item> LK;
   public static final RegistryObject<Item> THE_HANDOF_MUTANT_DROWNED_SPAWN_EGG;
   public static final RegistryObject<Item> HJ;
   public static final RegistryObject<Item> SW;
   public static final RegistryObject<Item> SW_2;
   public static final RegistryObject<Item> SW_1_SPAWN_EGG;
   public static final RegistryObject<Item> SOUL_SPAWN_EGG;
   public static final RegistryObject<Item> SOUL_2_SPAWN_EGG;
   public static final RegistryObject<Item> VG;
   public static final RegistryObject<Item> GREAT_SWORD_SPAWN_EGG;
   public static final RegistryObject<Item> MUTANT_BOGGED_SPAWN_EGG;
   public static final RegistryObject<Item> THEHANDOFMUTANTBOGGED_SPAWN_EGG;
   public static final RegistryObject<Item> MBB;
   public static final RegistryObject<Item> IRON_GOLEM_HELICOPTER_SPAWN_EGG;
   public static final RegistryObject<Item> THE_GUARD_OF_MUTANT_BOGGED_SPAWN_EGG;
   public static final RegistryObject<Item> ROCKET_SPAWN_EGG;
   public static final RegistryObject<Item> ROCKET_2;
   public static final RegistryObject<Item> ROCKET_3_SPAWN_EGG;
   public static final RegistryObject<Item> M;
   public static final RegistryObject<Item> WEAPONOFMUTANTWARDEN_SPAWN_EGG;
   public static final RegistryObject<Item> WOMW;
   public static final RegistryObject<Item> PUPPETOFMUTANTWARDEN_SPAWN_EGG;
   public static final RegistryObject<Item> SMOMW_SPAWN_EGG;
   public static final RegistryObject<Item> BOAT_SPAWN_EGG;
   public static final RegistryObject<Item> MUTANT_PIGLIN_BRUTE_SPAWN_EGG;
   public static final RegistryObject<Item> HANDOFMUTANTWITHER_SPAWN_EGG;
   public static final RegistryObject<Item> BLACK_HOLE_SPAWN_EGG;
   public static final RegistryObject<Item> HEADOFMUTANTWITHER_SPAWN_EGG;
   public static final RegistryObject<Item> TOWEROFMUTANTWITHER_SPAWN_EGG;
   public static final RegistryObject<Item> TOWEROFMUTANTWITHER_2_SPAWN_EGG;
   public static final RegistryObject<Item> MYSTERIOUS_POTION;
   public static final RegistryObject<Item> A_PART_OF_SIMULATED_COMMAND_BLOCK;
   public static final RegistryObject<Item> THETRUEESSENCE_SPAWN_EGG;
   public static final RegistryObject<Item> THE_QUEEN_MUTANT_SPAWN_EGG;
   public static final RegistryObject<Item> PB_SPAWN_EGG;
   public static final RegistryObject<Item> ITEM_OF_THE_QUEEN_MUTANT;

   static {
      REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, "themutantmobsmod");
      MUTANT_ZOMBIFIED_PIGLIN_SPAWN_EGG = REGISTRY.register("mutant_zombified_piglin_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_ZOMBIFIED_PIGLIN, -6711040, -1, new Item.Properties()));
      MUTANT_IRON_GOLEM_SPAWN_EGG = REGISTRY.register("mutant_iron_golem_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_IRON_GOLEM, -1, -1, new Item.Properties()));
      MUTANT_DROWNED_SPAWN_EGG = REGISTRY.register("mutant_drowned_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_DROWNED, -16751002, -1, new Item.Properties()));
      MUTANT_RAVAGER_SPAWN_EGG = REGISTRY.register("mutant_ravager_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_RAVAGER, -13421773, -1, new Item.Properties()));
      MUTANT_WARDEN_SPAWN_EGG = REGISTRY.register("mutant_warden_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_WARDEN, -16764109, -16777216, new Item.Properties()));
      GOLDS_SPAWN_EGG = REGISTRY.register("golds_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.GOLDS, -1, -1, new Item.Properties()));
      BLOCK_GOLD = REGISTRY.register("block_gold", () -> new BlockGoldItem());
      TD = REGISTRY.register("td", () -> new TdItem());
      MUTANT_ZOMBIE_VILLAGER_SPAWN_EGG = REGISTRY.register("mutant_zombie_villager_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_ZOMBIE_VILLAGER, -16751053, -10092544, new Item.Properties()));
      MUTANT_ZOGLIN_SPAWN_EGG = REGISTRY.register("mutant_zoglin_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_ZOGLIN, -10079488, -13408768, new Item.Properties()));
      MUTANT_DROWNED_1_SPAWN_EGG = REGISTRY.register("mutant_drowned_1_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_DROWNED_1, -1, -1, new Item.Properties()));
      MUTANT_DROWNED_2_SPAWN_EGG = REGISTRY.register("mutant_drowned_2_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_DROWNED_2, -1, -1, new Item.Properties()));
      MUTANT_DROWNED_3_SPAWN_EGG = REGISTRY.register("mutant_drowned_3_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_DROWNED_3, -1, -1, new Item.Properties()));
      HUNTER_GUN = REGISTRY.register("hunter_gun", () -> new HunterGunItem());
      SUPER_SONIC_BOOM = REGISTRY.register("super_sonic_boom", () -> new SuperSonicBoomItem());
      MUTANT_WITHER_SPAWN_EGG = REGISTRY.register("mutant_wither_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_WITHER, -16777216, -1, new Item.Properties()));
      SUPER_SKULL = REGISTRY.register("super_skull", () -> new SuperSkullItem());
      LAVA = REGISTRY.register("lava", () -> new LavaItem());
      MUTANT_STRIDER_SPAWN_EGG = REGISTRY.register("mutant_strider_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_STRIDER, -10092544, -1, new Item.Properties()));
      GIGAILLAGER_SPAWN_EGG = REGISTRY.register("gigaillager_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.GIGAILLAGER, -13421773, -16777216, new Item.Properties()));
      JJJ = REGISTRY.register("jjj", () -> new JjjItem());
      HHH = REGISTRY.register("hhh", () -> new HhhItem());
      GIGAILLAGER_V_2_SPAWN_EGG = REGISTRY.register("gigaillager_v_2_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.GIGAILLAGER_V_2, -1, -1, new Item.Properties()));
      MUTANTENDERDRAGON_SPAWN_EGG = REGISTRY.register("mutantenderdragon_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANTENDERDRAGON, -16777216, -13434829, new Item.Properties()));
      MAGICMADEBYMUTANTENDERDRAGON_SPAWN_EGG = REGISTRY.register("magicmadebymutantenderdragon_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MAGICMADEBYMUTANTENDERDRAGON, -1, -1, new Item.Properties()));
      MEDDS = REGISTRY.register("medds", () -> new MeddsItem());
      MUTANTSTRAY_SPAWN_EGG = REGISTRY.register("mutantstray_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANTSTRAY, -1, -16751002, new Item.Properties()));
      MSB = REGISTRY.register("msb", () -> new MsbItem());
      MSBU = REGISTRY.register("msbu", () -> new MsbuItem());
      MUTANT_NETHERITE_GOLEM_SPAWN_EGG = REGISTRY.register("mutant_netherite_golem_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_NETHERITE_GOLEM, -16777216, -13434880, new Item.Properties()));
      MNGW = REGISTRY.register("mngw", () -> new MngwItem());
      SLAM = REGISTRY.register("slam", () -> new SlamItem());
      MUTANT_SNIFFER_SPAWN_EGG = REGISTRY.register("mutant_sniffer_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_SNIFFER, -10092544, -16751104, new Item.Properties()));
      ANCIENT_TREE_SPAWN_EGG = REGISTRY.register("ancient_tree_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.ANCIENT_TREE, -1, -1, new Item.Properties()));
      TRFH = REGISTRY.register("trfh", () -> new TrfhItem());
      MUTANT_GHAST_SPAWN_EGG = REGISTRY.register("mutant_ghast_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_GHAST, -1, -10092544, new Item.Properties()));
      MGRI = REGISTRY.register("mgri", () -> new MgriItem());
      MMBMG_SPAWN_EGG = REGISTRY.register("mmbmg_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MMBMG, -1, -1, new Item.Properties()));
      MGRI_2 = REGISTRY.register("mgri_2", () -> new Mgri2Item());
      ALPHA_MUTANT_IRON_GOLEM_SPAWN_EGG = REGISTRY.register("alpha_mutant_iron_golem_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.ALPHA_MUTANT_IRON_GOLEM, -1, -6710887, new Item.Properties()));
      AMIRI = REGISTRY.register("amiri", () -> new AmiriItem());
      TRYU_SPAWN_EGG = REGISTRY.register("tryu_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.TRYU, -1, -1, new Item.Properties()));
      LK = REGISTRY.register("lk", () -> new LkItem());
      THE_HANDOF_MUTANT_DROWNED_SPAWN_EGG = REGISTRY.register("the_handof_mutant_drowned_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.THE_HANDOF_MUTANT_DROWNED, -1, -1, new Item.Properties()));
      HJ = REGISTRY.register("hj", () -> new HjItem());
      SW = REGISTRY.register("sw", () -> new SwItem());
      SW_2 = REGISTRY.register("sw_2", () -> new Sw2Item());
      SW_1_SPAWN_EGG = REGISTRY.register("sw_1_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.SW_1, -1, -1, new Item.Properties()));
      SOUL_SPAWN_EGG = REGISTRY.register("soul_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.SOUL, -1, -1, new Item.Properties()));
      SOUL_2_SPAWN_EGG = REGISTRY.register("soul_2_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.SOUL_2, -1, -1, new Item.Properties()));
      VG = REGISTRY.register("vg", () -> new VgItem());
      GREAT_SWORD_SPAWN_EGG = REGISTRY.register("great_sword_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.GREAT_SWORD, -1, -1, new Item.Properties()));
      MUTANT_BOGGED_SPAWN_EGG = REGISTRY.register("mutant_bogged_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_BOGGED, -16737997, -1, new Item.Properties()));
      THEHANDOFMUTANTBOGGED_SPAWN_EGG = REGISTRY.register("thehandofmutantbogged_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.THEHANDOFMUTANTBOGGED, -1, -1, new Item.Properties()));
      MBB = REGISTRY.register("mbb", () -> new MbbItem());
      IRON_GOLEM_HELICOPTER_SPAWN_EGG = REGISTRY.register("iron_golem_helicopter_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.IRON_GOLEM_HELICOPTER, -1, -1, new Item.Properties()));
      THE_GUARD_OF_MUTANT_BOGGED_SPAWN_EGG = REGISTRY.register("the_guard_of_mutant_bogged_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.THE_GUARD_OF_MUTANT_BOGGED, -1, -1, new Item.Properties()));
      ROCKET_SPAWN_EGG = REGISTRY.register("rocket_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.ROCKET, -1, -1, new Item.Properties()));
      ROCKET_2 = REGISTRY.register("rocket_2", () -> new Rocket2Item());
      ROCKET_3_SPAWN_EGG = REGISTRY.register("rocket_3_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.ROCKET_3, -1, -1, new Item.Properties()));
      M = REGISTRY.register("m", () -> new MItem());
      WEAPONOFMUTANTWARDEN_SPAWN_EGG = REGISTRY.register("weaponofmutantwarden_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.WEAPONOFMUTANTWARDEN, -1, -1, new Item.Properties()));
      WOMW = REGISTRY.register("womw", () -> new WomwItem());
      PUPPETOFMUTANTWARDEN_SPAWN_EGG = REGISTRY.register("puppetofmutantwarden_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.PUPPETOFMUTANTWARDEN, -1, -1, new Item.Properties()));
      SMOMW_SPAWN_EGG = REGISTRY.register("smomw_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.SMOMW, -1, -1, new Item.Properties()));
      BOAT_SPAWN_EGG = REGISTRY.register("boat_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.BOAT, -1, -1, new Item.Properties()));
      MUTANT_PIGLIN_BRUTE_SPAWN_EGG = REGISTRY.register("mutant_piglin_brute_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.MUTANT_PIGLIN_BRUTE, -26368, -3355648, new Item.Properties()));
      HANDOFMUTANTWITHER_SPAWN_EGG = REGISTRY.register("handofmutantwither_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.HANDOFMUTANTWITHER, -1, -1, new Item.Properties()));
      BLACK_HOLE_SPAWN_EGG = REGISTRY.register("black_hole_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.BLACK_HOLE, -1, -1, new Item.Properties()));
      HEADOFMUTANTWITHER_SPAWN_EGG = REGISTRY.register("headofmutantwither_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.HEADOFMUTANTWITHER, -1, -1, new Item.Properties()));
      TOWEROFMUTANTWITHER_SPAWN_EGG = REGISTRY.register("towerofmutantwither_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.TOWEROFMUTANTWITHER, -1, -1, new Item.Properties()));
      TOWEROFMUTANTWITHER_2_SPAWN_EGG = REGISTRY.register("towerofmutantwither_2_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.TOWEROFMUTANTWITHER_2, -1, -1, new Item.Properties()));
      MYSTERIOUS_POTION = REGISTRY.register("mysterious_potion", () -> new MysteriousPotionItem());
      A_PART_OF_SIMULATED_COMMAND_BLOCK = REGISTRY.register("a_part_of_simulated_command_block", () -> new APartOfSimulatedCommandBlockItem());
      THETRUEESSENCE_SPAWN_EGG = REGISTRY.register("thetrueessence_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.THETRUEESSENCE, -1, -1, new Item.Properties()));
      THE_QUEEN_MUTANT_SPAWN_EGG = REGISTRY.register("the_queen_mutant_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.THE_QUEEN_MUTANT, -13434829, -10092442, new Item.Properties()));
      PB_SPAWN_EGG = REGISTRY.register("pb_spawn_egg", () -> new ForgeSpawnEggItem(ThemutantmobsmodModEntities.PB, -1, -1, new Item.Properties()));
      ITEM_OF_THE_QUEEN_MUTANT = REGISTRY.register("item_of_the_queen_mutant", () -> new ItemOfTheQueenMutantItem());
   }
}
