package net.mcreator.tbm.init;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ThemutantmobsmodModSounds {
   public static final DeferredRegister<SoundEvent> REGISTRY;
   public static final RegistryObject<SoundEvent> SIREN;
   public static final RegistryObject<SoundEvent> ST;
   public static final RegistryObject<SoundEvent> WO;
   public static final RegistryObject<SoundEvent> HUR;
   public static final RegistryObject<SoundEvent> HUR2;
   public static final RegistryObject<SoundEvent> AT;
   public static final RegistryObject<SoundEvent> C;
   public static final RegistryObject<SoundEvent> CHASE;
   public static final RegistryObject<SoundEvent> FG6U;
   public static final RegistryObject<SoundEvent> MDA1;
   public static final RegistryObject<SoundEvent> MDA;
   public static final RegistryObject<SoundEvent> MDH;
   public static final RegistryObject<SoundEvent> MHH;
   public static final RegistryObject<SoundEvent> MHR;
   public static final RegistryObject<SoundEvent> MHE;
   public static final RegistryObject<SoundEvent> MHA;
   public static final RegistryObject<SoundEvent> MZVS;
   public static final RegistryObject<SoundEvent> DAD;
   public static final RegistryObject<SoundEvent> TT;
   public static final RegistryObject<SoundEvent> MST;
   public static final RegistryObject<SoundEvent> MWT;
   public static final RegistryObject<SoundEvent> ENCHASE;
   public static final RegistryObject<SoundEvent> GA;
   public static final RegistryObject<SoundEvent> MMGG;
   public static final RegistryObject<SoundEvent> KKK;
   public static final RegistryObject<SoundEvent> GHD;
   public static final RegistryObject<SoundEvent> GU;
   public static final RegistryObject<SoundEvent> MEDH;
   public static final RegistryObject<SoundEvent> KLJ;
   public static final RegistryObject<SoundEvent> LPL;
   public static final RegistryObject<SoundEvent> GH;
   public static final RegistryObject<SoundEvent> II;
   public static final RegistryObject<SoundEvent> MGBT;
   public static final RegistryObject<SoundEvent> MGS2;
   public static final RegistryObject<SoundEvent> GGILGTM;
   public static final RegistryObject<SoundEvent> MWBBT;
   public static final RegistryObject<SoundEvent> SW1;
   public static final RegistryObject<SoundEvent> SOUL;
   public static final RegistryObject<SoundEvent> EXPL;
   public static final RegistryObject<SoundEvent> SW2;
   public static final RegistryObject<SoundEvent> SO1;
   public static final RegistryObject<SoundEvent> SO2;
   public static final RegistryObject<SoundEvent> SEFE2;
   public static final RegistryObject<SoundEvent> MBSHOT;
   public static final RegistryObject<SoundEvent> MBTB;
   public static final RegistryObject<SoundEvent> SSSE;
   public static final RegistryObject<SoundEvent> UNBBT;
   public static final RegistryObject<SoundEvent> BFD;
   public static final RegistryObject<SoundEvent> TQM;

   static {
      REGISTRY = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, "themutantmobsmod");
      SIREN = REGISTRY.register("siren", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "siren")));
      ST = REGISTRY.register("st", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "st")));
      WO = REGISTRY.register("wo", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "wo")));
      HUR = REGISTRY.register("hur", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "hur")));
      HUR2 = REGISTRY.register("hur2", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "hur2")));
      AT = REGISTRY.register("at", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "at")));
      C = REGISTRY.register("c", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "c")));
      CHASE = REGISTRY.register("chase", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "chase")));
      FG6U = REGISTRY.register("fg6u", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "fg6u")));
      MDA1 = REGISTRY.register("mda1", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mda1")));
      MDA = REGISTRY.register("mda", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mda")));
      MDH = REGISTRY.register("mdh", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mdh")));
      MHH = REGISTRY.register("mhh", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mhh")));
      MHR = REGISTRY.register("mhr", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mhr")));
      MHE = REGISTRY.register("mhe", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mhe")));
      MHA = REGISTRY.register("mha", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mha")));
      MZVS = REGISTRY.register("mzvs", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mzvs")));
      DAD = REGISTRY.register("dad", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "dad")));
      TT = REGISTRY.register("tt", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "tt")));
      MST = REGISTRY.register("mst", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mst")));
      MWT = REGISTRY.register("mwt", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mwt")));
      ENCHASE = REGISTRY.register("enchase", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "enchase")));
      GA = REGISTRY.register("ga", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "ga")));
      MMGG = REGISTRY.register("mmgg", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mmgg")));
      KKK = REGISTRY.register("kkk", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "kkk")));
      GHD = REGISTRY.register("ghd", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "ghd")));
      GU = REGISTRY.register("gu", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "gu")));
      MEDH = REGISTRY.register("medh", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "medh")));
      KLJ = REGISTRY.register("klj", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "klj")));
      LPL = REGISTRY.register("lpl", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "lpl")));
      GH = REGISTRY.register("gh", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "gh")));
      II = REGISTRY.register("ii", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "ii")));
      MGBT = REGISTRY.register("mgbt", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mgbt")));
      MGS2 = REGISTRY.register("mgs2", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mgs2")));
      GGILGTM = REGISTRY.register("ggilgtm", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "ggilgtm")));
      MWBBT = REGISTRY.register("mwbbt", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mwbbt")));
      SW1 = REGISTRY.register("sw1", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "sw1")));
      SOUL = REGISTRY.register("soul", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "soul")));
      EXPL = REGISTRY.register("expl", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "expl")));
      SW2 = REGISTRY.register("sw2", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "sw2")));
      SO1 = REGISTRY.register("so1", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "so1")));
      SO2 = REGISTRY.register("so2", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "so2")));
      SEFE2 = REGISTRY.register("sefe2", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "sefe2")));
      MBSHOT = REGISTRY.register("mbshot", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mbshot")));
      MBTB = REGISTRY.register("mbtb", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "mbtb")));
      SSSE = REGISTRY.register("ssse", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "ssse")));
      UNBBT = REGISTRY.register("unbbt", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "unbbt")));
      BFD = REGISTRY.register("bfd", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "bfd")));
      TQM = REGISTRY.register("tqm", () -> SoundEvent.m_262824_(new ResourceLocation("themutantmobsmod", "tqm")));
   }
}
