package net.mcreator.tbm.init;

import net.mcreator.tbm.entity.AlphaMutantIronGolemEntity;
import net.mcreator.tbm.entity.AmiriEntity;
import net.mcreator.tbm.entity.AncientTreeEntity;
import net.mcreator.tbm.entity.BlackHoleEntity;
import net.mcreator.tbm.entity.BlockGoldEntity;
import net.mcreator.tbm.entity.BoatEntity;
import net.mcreator.tbm.entity.GigaillagerEntity;
import net.mcreator.tbm.entity.GigaillagerV2Entity;
import net.mcreator.tbm.entity.GoldsEntity;
import net.mcreator.tbm.entity.GreatSwordEntity;
import net.mcreator.tbm.entity.HandofmutantwitherEntity;
import net.mcreator.tbm.entity.HeadofmutantwitherEntity;
import net.mcreator.tbm.entity.HhhEntity;
import net.mcreator.tbm.entity.HjEntity;
import net.mcreator.tbm.entity.HunterGunEntity;
import net.mcreator.tbm.entity.IronGolemHelicopterEntity;
import net.mcreator.tbm.entity.JjjEntity;
import net.mcreator.tbm.entity.LavaEntity;
import net.mcreator.tbm.entity.LkEntity;
import net.mcreator.tbm.entity.MagicbymutantenderdragonEntity;
import net.mcreator.tbm.entity.MbbEntity;
import net.mcreator.tbm.entity.MeddsEntity;
import net.mcreator.tbm.entity.Mgri2Entity;
import net.mcreator.tbm.entity.MgriEntity;
import net.mcreator.tbm.entity.MmbmgEntity;
import net.mcreator.tbm.entity.MngwEntity;
import net.mcreator.tbm.entity.MsbEntity;
import net.mcreator.tbm.entity.MsbuEntity;
import net.mcreator.tbm.entity.MutantBoggedEntity;
import net.mcreator.tbm.entity.MutantDrowned1Entity;
import net.mcreator.tbm.entity.MutantDrowned2Entity;
import net.mcreator.tbm.entity.MutantDrowned3Entity;
import net.mcreator.tbm.entity.MutantDrownedEntity;
import net.mcreator.tbm.entity.MutantGhastEntity;
import net.mcreator.tbm.entity.MutantIronGolemEntity;
import net.mcreator.tbm.entity.MutantNetheriteGolemEntity;
import net.mcreator.tbm.entity.MutantPiglinBruteEntity;
import net.mcreator.tbm.entity.MutantRavagerEntity;
import net.mcreator.tbm.entity.MutantSnifferEntity;
import net.mcreator.tbm.entity.MutantStriderEntity;
import net.mcreator.tbm.entity.MutantWardenEntity;
import net.mcreator.tbm.entity.MutantWitherEntity;
import net.mcreator.tbm.entity.MutantZoglinEntity;
import net.mcreator.tbm.entity.MutantZombieVillagerEntity;
import net.mcreator.tbm.entity.MutantZombiefiedPiglinEntity;
import net.mcreator.tbm.entity.MutantenderdragonEntity;
import net.mcreator.tbm.entity.MutantstrayEntity;
import net.mcreator.tbm.entity.PBEntity;
import net.mcreator.tbm.entity.PuppetofmutantwardenEntity;
import net.mcreator.tbm.entity.Rocket2Entity;
import net.mcreator.tbm.entity.Rocket3Entity;
import net.mcreator.tbm.entity.RocketEntity;
import net.mcreator.tbm.entity.SlamEntity;
import net.mcreator.tbm.entity.SmomwEntity;
import net.mcreator.tbm.entity.Soul2Entity;
import net.mcreator.tbm.entity.SoulEntity;
import net.mcreator.tbm.entity.SuperSkullEntity;
import net.mcreator.tbm.entity.SuperSonicBoomEntity;
import net.mcreator.tbm.entity.Sw1Entity;
import net.mcreator.tbm.entity.Sw2Entity;
import net.mcreator.tbm.entity.SwEntity;
import net.mcreator.tbm.entity.TdEntity;
import net.mcreator.tbm.entity.TheGuardOfMutantBoggedEntity;
import net.mcreator.tbm.entity.TheHandofMutantDrownedEntity;
import net.mcreator.tbm.entity.TheQueenMutantEntity;
import net.mcreator.tbm.entity.ThehandofmutantboggedEntity;
import net.mcreator.tbm.entity.ThetrueessenceEntity;
import net.mcreator.tbm.entity.Towerofmutantwither2Entity;
import net.mcreator.tbm.entity.TowerofmutantwitherEntity;
import net.mcreator.tbm.entity.TrfhEntity;
import net.mcreator.tbm.entity.TryuEntity;
import net.mcreator.tbm.entity.VgEntity;
import net.mcreator.tbm.entity.WeaponofmutantwardenEntity;
import net.mcreator.tbm.entity.WomwEntity;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.entity.EntityType.Builder;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

@EventBusSubscriber(
   bus = Bus.MOD
)
public class ThemutantmobsmodModEntities {
   public static final DeferredRegister<EntityType<?>> REGISTRY;
   public static final RegistryObject<EntityType<MutantZombiefiedPiglinEntity>> MUTANT_ZOMBIFIED_PIGLIN;
   public static final RegistryObject<EntityType<MutantIronGolemEntity>> MUTANT_IRON_GOLEM;
   public static final RegistryObject<EntityType<MutantDrownedEntity>> MUTANT_DROWNED;
   public static final RegistryObject<EntityType<MutantRavagerEntity>> MUTANT_RAVAGER;
   public static final RegistryObject<EntityType<MutantWardenEntity>> MUTANT_WARDEN;
   public static final RegistryObject<EntityType<GoldsEntity>> GOLDS;
   public static final RegistryObject<EntityType<BlockGoldEntity>> BLOCK_GOLD;
   public static final RegistryObject<EntityType<TdEntity>> TD;
   public static final RegistryObject<EntityType<MutantZombieVillagerEntity>> MUTANT_ZOMBIE_VILLAGER;
   public static final RegistryObject<EntityType<MutantZoglinEntity>> MUTANT_ZOGLIN;
   public static final RegistryObject<EntityType<MutantDrowned1Entity>> MUTANT_DROWNED_1;
   public static final RegistryObject<EntityType<MutantDrowned2Entity>> MUTANT_DROWNED_2;
   public static final RegistryObject<EntityType<MutantDrowned3Entity>> MUTANT_DROWNED_3;
   public static final RegistryObject<EntityType<HunterGunEntity>> HUNTER_GUN;
   public static final RegistryObject<EntityType<SuperSonicBoomEntity>> SUPER_SONIC_BOOM;
   public static final RegistryObject<EntityType<MutantWitherEntity>> MUTANT_WITHER;
   public static final RegistryObject<EntityType<SuperSkullEntity>> SUPER_SKULL;
   public static final RegistryObject<EntityType<LavaEntity>> LAVA;
   public static final RegistryObject<EntityType<MutantStriderEntity>> MUTANT_STRIDER;
   public static final RegistryObject<EntityType<GigaillagerEntity>> GIGAILLAGER;
   public static final RegistryObject<EntityType<JjjEntity>> JJJ;
   public static final RegistryObject<EntityType<HhhEntity>> HHH;
   public static final RegistryObject<EntityType<GigaillagerV2Entity>> GIGAILLAGER_V_2;
   public static final RegistryObject<EntityType<MutantenderdragonEntity>> MUTANTENDERDRAGON;
   public static final RegistryObject<EntityType<MagicbymutantenderdragonEntity>> MAGICMADEBYMUTANTENDERDRAGON;
   public static final RegistryObject<EntityType<MeddsEntity>> MEDDS;
   public static final RegistryObject<EntityType<MutantstrayEntity>> MUTANTSTRAY;
   public static final RegistryObject<EntityType<MsbEntity>> MSB;
   public static final RegistryObject<EntityType<MsbuEntity>> MSBU;
   public static final RegistryObject<EntityType<MutantNetheriteGolemEntity>> MUTANT_NETHERITE_GOLEM;
   public static final RegistryObject<EntityType<MngwEntity>> MNGW;
   public static final RegistryObject<EntityType<SlamEntity>> SLAM;
   public static final RegistryObject<EntityType<MutantSnifferEntity>> MUTANT_SNIFFER;
   public static final RegistryObject<EntityType<AncientTreeEntity>> ANCIENT_TREE;
   public static final RegistryObject<EntityType<TrfhEntity>> TRFH;
   public static final RegistryObject<EntityType<MutantGhastEntity>> MUTANT_GHAST;
   public static final RegistryObject<EntityType<MgriEntity>> MGRI;
   public static final RegistryObject<EntityType<MmbmgEntity>> MMBMG;
   public static final RegistryObject<EntityType<Mgri2Entity>> MGRI_2;
   public static final RegistryObject<EntityType<AlphaMutantIronGolemEntity>> ALPHA_MUTANT_IRON_GOLEM;
   public static final RegistryObject<EntityType<AmiriEntity>> AMIRI;
   public static final RegistryObject<EntityType<TryuEntity>> TRYU;
   public static final RegistryObject<EntityType<LkEntity>> LK;
   public static final RegistryObject<EntityType<TheHandofMutantDrownedEntity>> THE_HANDOF_MUTANT_DROWNED;
   public static final RegistryObject<EntityType<HjEntity>> HJ;
   public static final RegistryObject<EntityType<SwEntity>> SW;
   public static final RegistryObject<EntityType<Sw2Entity>> SW_2;
   public static final RegistryObject<EntityType<Sw1Entity>> SW_1;
   public static final RegistryObject<EntityType<SoulEntity>> SOUL;
   public static final RegistryObject<EntityType<Soul2Entity>> SOUL_2;
   public static final RegistryObject<EntityType<VgEntity>> VG;
   public static final RegistryObject<EntityType<GreatSwordEntity>> GREAT_SWORD;
   public static final RegistryObject<EntityType<MutantBoggedEntity>> MUTANT_BOGGED;
   public static final RegistryObject<EntityType<ThehandofmutantboggedEntity>> THEHANDOFMUTANTBOGGED;
   public static final RegistryObject<EntityType<MbbEntity>> MBB;
   public static final RegistryObject<EntityType<IronGolemHelicopterEntity>> IRON_GOLEM_HELICOPTER;
   public static final RegistryObject<EntityType<TheGuardOfMutantBoggedEntity>> THE_GUARD_OF_MUTANT_BOGGED;
   public static final RegistryObject<EntityType<RocketEntity>> ROCKET;
   public static final RegistryObject<EntityType<Rocket2Entity>> ROCKET_2;
   public static final RegistryObject<EntityType<Rocket3Entity>> ROCKET_3;
   public static final RegistryObject<EntityType<WeaponofmutantwardenEntity>> WEAPONOFMUTANTWARDEN;
   public static final RegistryObject<EntityType<WomwEntity>> WOMW;
   public static final RegistryObject<EntityType<PuppetofmutantwardenEntity>> PUPPETOFMUTANTWARDEN;
   public static final RegistryObject<EntityType<SmomwEntity>> SMOMW;
   public static final RegistryObject<EntityType<BoatEntity>> BOAT;
   public static final RegistryObject<EntityType<MutantPiglinBruteEntity>> MUTANT_PIGLIN_BRUTE;
   public static final RegistryObject<EntityType<HandofmutantwitherEntity>> HANDOFMUTANTWITHER;
   public static final RegistryObject<EntityType<BlackHoleEntity>> BLACK_HOLE;
   public static final RegistryObject<EntityType<HeadofmutantwitherEntity>> HEADOFMUTANTWITHER;
   public static final RegistryObject<EntityType<TowerofmutantwitherEntity>> TOWEROFMUTANTWITHER;
   public static final RegistryObject<EntityType<Towerofmutantwither2Entity>> TOWEROFMUTANTWITHER_2;
   public static final RegistryObject<EntityType<ThetrueessenceEntity>> THETRUEESSENCE;
   public static final RegistryObject<EntityType<TheQueenMutantEntity>> THE_QUEEN_MUTANT;
   public static final RegistryObject<EntityType<PBEntity>> PB;

   private static <T extends Entity> RegistryObject<EntityType<T>> register(String registryname, EntityType.Builder<T> entityTypeBuilder) {
      return REGISTRY.register(registryname, () -> entityTypeBuilder.m_20712_(registryname));
   }

   @SubscribeEvent
   public static void init(FMLCommonSetupEvent event) {
      event.enqueueWork(() -> {
         MutantZombiefiedPiglinEntity.init();
         MutantIronGolemEntity.init();
         MutantDrownedEntity.init();
         MutantRavagerEntity.init();
         MutantWardenEntity.init();
         GoldsEntity.init();
         MutantZombieVillagerEntity.init();
         MutantZoglinEntity.init();
         MutantDrowned1Entity.init();
         MutantDrowned2Entity.init();
         MutantDrowned3Entity.init();
         MutantWitherEntity.init();
         MutantStriderEntity.init();
         GigaillagerEntity.init();
         GigaillagerV2Entity.init();
         MutantenderdragonEntity.init();
         MagicbymutantenderdragonEntity.init();
         MutantstrayEntity.init();
         MutantNetheriteGolemEntity.init();
         MutantSnifferEntity.init();
         AncientTreeEntity.init();
         MutantGhastEntity.init();
         MmbmgEntity.init();
         AlphaMutantIronGolemEntity.init();
         TryuEntity.init();
         TheHandofMutantDrownedEntity.init();
         Sw1Entity.init();
         SoulEntity.init();
         Soul2Entity.init();
         GreatSwordEntity.init();
         MutantBoggedEntity.init();
         ThehandofmutantboggedEntity.init();
         IronGolemHelicopterEntity.init();
         TheGuardOfMutantBoggedEntity.init();
         RocketEntity.init();
         Rocket3Entity.init();
         WeaponofmutantwardenEntity.init();
         PuppetofmutantwardenEntity.init();
         SmomwEntity.init();
         BoatEntity.init();
         MutantPiglinBruteEntity.init();
         HandofmutantwitherEntity.init();
         BlackHoleEntity.init();
         HeadofmutantwitherEntity.init();
         TowerofmutantwitherEntity.init();
         Towerofmutantwither2Entity.init();
         ThetrueessenceEntity.init();
         TheQueenMutantEntity.init();
         PBEntity.init();
      });
   }

   @SubscribeEvent
   public static void registerAttributes(EntityAttributeCreationEvent event) {
      event.put((EntityType)MUTANT_ZOMBIFIED_PIGLIN.get(), MutantZombiefiedPiglinEntity.createAttributes().m_22265_());
      event.put((EntityType)MUTANT_IRON_GOLEM.get(), MutantIronGolemEntity.m_28883_().m_22265_());
      event.put((EntityType)MUTANT_DROWNED.get(), MutantDrownedEntity.m_34328_().m_22265_());
      event.put((EntityType)MUTANT_RAVAGER.get(), MutantRavagerEntity.createAttributes().m_22265_());
      event.put((EntityType)MUTANT_WARDEN.get(), MutantWardenEntity.createAttributes().m_22265_());
      event.put((EntityType)GOLDS.get(), GoldsEntity.createAttributes().m_22265_());
      event.put((EntityType)MUTANT_ZOMBIE_VILLAGER.get(), MutantZombieVillagerEntity.m_34328_().m_22265_());
      event.put((EntityType)MUTANT_ZOGLIN.get(), MutantZoglinEntity.createAttributes().m_22265_());
      event.put((EntityType)MUTANT_DROWNED_1.get(), MutantDrowned1Entity.m_34328_().m_22265_());
      event.put((EntityType)MUTANT_DROWNED_2.get(), MutantDrowned2Entity.m_34328_().m_22265_());
      event.put((EntityType)MUTANT_DROWNED_3.get(), MutantDrowned3Entity.m_34328_().m_22265_());
      event.put((EntityType)MUTANT_WITHER.get(), MutantWitherEntity.createAttributes().m_22265_());
      event.put((EntityType)MUTANT_STRIDER.get(), MutantStriderEntity.createAttributes().m_22265_());
      event.put((EntityType)GIGAILLAGER.get(), GigaillagerEntity.createAttributes().m_22265_());
      event.put((EntityType)GIGAILLAGER_V_2.get(), GigaillagerV2Entity.createAttributes().m_22265_());
      event.put((EntityType)MUTANTENDERDRAGON.get(), MutantenderdragonEntity.createAttributes().m_22265_());
      event.put((EntityType)MAGICMADEBYMUTANTENDERDRAGON.get(), MagicbymutantenderdragonEntity.createAttributes().m_22265_());
      event.put((EntityType)MUTANTSTRAY.get(), MutantstrayEntity.m_32166_().m_22265_());
      event.put((EntityType)MUTANT_NETHERITE_GOLEM.get(), MutantNetheriteGolemEntity.m_28883_().m_22265_());
      event.put((EntityType)MUTANT_SNIFFER.get(), MutantSnifferEntity.createAttributes().m_22265_());
      event.put((EntityType)ANCIENT_TREE.get(), AncientTreeEntity.createAttributes().m_22265_());
      event.put((EntityType)MUTANT_GHAST.get(), MutantGhastEntity.createAttributes().m_22265_());
      event.put((EntityType)MMBMG.get(), MmbmgEntity.createAttributes().m_22265_());
      event.put((EntityType)ALPHA_MUTANT_IRON_GOLEM.get(), AlphaMutantIronGolemEntity.m_28883_().m_22265_());
      event.put((EntityType)TRYU.get(), TryuEntity.createAttributes().m_22265_());
      event.put((EntityType)THE_HANDOF_MUTANT_DROWNED.get(), TheHandofMutantDrownedEntity.m_34328_().m_22265_());
      event.put((EntityType)SW_1.get(), Sw1Entity.createAttributes().m_22265_());
      event.put((EntityType)SOUL.get(), SoulEntity.createAttributes().m_22265_());
      event.put((EntityType)SOUL_2.get(), Soul2Entity.createAttributes().m_22265_());
      event.put((EntityType)GREAT_SWORD.get(), GreatSwordEntity.createAttributes().m_22265_());
      event.put((EntityType)MUTANT_BOGGED.get(), MutantBoggedEntity.m_32166_().m_22265_());
      event.put((EntityType)THEHANDOFMUTANTBOGGED.get(), ThehandofmutantboggedEntity.m_34328_().m_22265_());
      event.put((EntityType)IRON_GOLEM_HELICOPTER.get(), IronGolemHelicopterEntity.m_28883_().m_22265_());
      event.put((EntityType)THE_GUARD_OF_MUTANT_BOGGED.get(), TheGuardOfMutantBoggedEntity.m_32166_().m_22265_());
      event.put((EntityType)ROCKET.get(), RocketEntity.m_28883_().m_22265_());
      event.put((EntityType)ROCKET_3.get(), Rocket3Entity.createAttributes().m_22265_());
      event.put((EntityType)WEAPONOFMUTANTWARDEN.get(), WeaponofmutantwardenEntity.createAttributes().m_22265_());
      event.put((EntityType)PUPPETOFMUTANTWARDEN.get(), PuppetofmutantwardenEntity.createAttributes().m_22265_());
      event.put((EntityType)SMOMW.get(), SmomwEntity.createAttributes().m_22265_());
      event.put((EntityType)BOAT.get(), BoatEntity.createAttributes().m_22265_());
      event.put((EntityType)MUTANT_PIGLIN_BRUTE.get(), MutantPiglinBruteEntity.createAttributes().m_22265_());
      event.put((EntityType)HANDOFMUTANTWITHER.get(), HandofmutantwitherEntity.createAttributes().m_22265_());
      event.put((EntityType)BLACK_HOLE.get(), BlackHoleEntity.createAttributes().m_22265_());
      event.put((EntityType)HEADOFMUTANTWITHER.get(), HeadofmutantwitherEntity.createAttributes().m_22265_());
      event.put((EntityType)TOWEROFMUTANTWITHER.get(), TowerofmutantwitherEntity.createAttributes().m_22265_());
      event.put((EntityType)TOWEROFMUTANTWITHER_2.get(), Towerofmutantwither2Entity.createAttributes().m_22265_());
      event.put((EntityType)THETRUEESSENCE.get(), ThetrueessenceEntity.createAttributes().m_22265_());
      event.put((EntityType)THE_QUEEN_MUTANT.get(), TheQueenMutantEntity.createAttributes().m_22265_());
      event.put((EntityType)PB.get(), PBEntity.createAttributes().m_22265_());
   }

   static {
      REGISTRY = DeferredRegister.create(ForgeRegistries.ENTITY_TYPES, "themutantmobsmod");
      MUTANT_ZOMBIFIED_PIGLIN = register("mutant_zombified_piglin", Builder.m_20704_(MutantZombiefiedPiglinEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantZombiefiedPiglinEntity::new).m_20719_().m_20699_(0.6F, 3.0F));
      MUTANT_IRON_GOLEM = register("mutant_iron_golem", Builder.m_20704_(MutantIronGolemEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantIronGolemEntity::new).m_20719_().m_20699_(0.6F, 5.0F));
      MUTANT_DROWNED = register("mutant_drowned", Builder.m_20704_(MutantDrownedEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantDrownedEntity::new).m_20719_().m_20699_(1.0F, 2.5F));
      MUTANT_RAVAGER = register("mutant_ravager", Builder.m_20704_(MutantRavagerEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantRavagerEntity::new).m_20719_().m_20699_(2.3F, 12.0F));
      MUTANT_WARDEN = register("mutant_warden", Builder.m_20704_(MutantWardenEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantWardenEntity::new).m_20719_().m_20699_(2.0F, 8.0F));
      GOLDS = register("golds", Builder.m_20704_(GoldsEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(GoldsEntity::new).m_20699_(0.6F, 1.8F));
      BLOCK_GOLD = register("projectile_block_gold", Builder.m_20704_(BlockGoldEntity::new, MobCategory.MISC).setCustomClientFactory(BlockGoldEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      TD = register("projectile_td", Builder.m_20704_(TdEntity::new, MobCategory.MISC).setCustomClientFactory(TdEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      MUTANT_ZOMBIE_VILLAGER = register("mutant_zombie_villager", Builder.m_20704_(MutantZombieVillagerEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantZombieVillagerEntity::new).m_20719_().m_20699_(0.6F, 1.8F));
      MUTANT_ZOGLIN = register("mutant_zoglin", Builder.m_20704_(MutantZoglinEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantZoglinEntity::new).m_20719_().m_20699_(2.0F, 3.0F));
      MUTANT_DROWNED_1 = register("mutant_drowned_1", Builder.m_20704_(MutantDrowned1Entity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantDrowned1Entity::new).m_20719_().m_20699_(1.0F, 2.5F));
      MUTANT_DROWNED_2 = register("mutant_drowned_2", Builder.m_20704_(MutantDrowned2Entity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantDrowned2Entity::new).m_20719_().m_20699_(1.0F, 2.5F));
      MUTANT_DROWNED_3 = register("mutant_drowned_3", Builder.m_20704_(MutantDrowned3Entity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantDrowned3Entity::new).m_20719_().m_20699_(1.0F, 2.5F));
      HUNTER_GUN = register("projectile_hunter_gun", Builder.m_20704_(HunterGunEntity::new, MobCategory.MISC).setCustomClientFactory(HunterGunEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      SUPER_SONIC_BOOM = register("projectile_super_sonic_boom", Builder.m_20704_(SuperSonicBoomEntity::new, MobCategory.MISC).setCustomClientFactory(SuperSonicBoomEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      MUTANT_WITHER = register("mutant_wither", Builder.m_20704_(MutantWitherEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantWitherEntity::new).m_20719_().m_20699_(2.0F, 4.5F));
      SUPER_SKULL = register("projectile_super_skull", Builder.m_20704_(SuperSkullEntity::new, MobCategory.MISC).setCustomClientFactory(SuperSkullEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      LAVA = register("projectile_lava", Builder.m_20704_(LavaEntity::new, MobCategory.MISC).setCustomClientFactory(LavaEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      MUTANT_STRIDER = register("mutant_strider", Builder.m_20704_(MutantStriderEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantStriderEntity::new).m_20719_().m_20699_(1.2F, 10.0F));
      GIGAILLAGER = register("gigaillager", Builder.m_20704_(GigaillagerEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(GigaillagerEntity::new).m_20719_().m_20699_(0.6F, 2.0F));
      JJJ = register("projectile_jjj", Builder.m_20704_(JjjEntity::new, MobCategory.MISC).setCustomClientFactory(JjjEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      HHH = register("projectile_hhh", Builder.m_20704_(HhhEntity::new, MobCategory.MISC).setCustomClientFactory(HhhEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      GIGAILLAGER_V_2 = register("gigaillager_v_2", Builder.m_20704_(GigaillagerV2Entity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(GigaillagerV2Entity::new).m_20719_().m_20699_(0.6F, 1.8F));
      MUTANTENDERDRAGON = register("mutantenderdragon", Builder.m_20704_(MutantenderdragonEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantenderdragonEntity::new).m_20719_().m_20699_(2.3F, 7.0F));
      MAGICMADEBYMUTANTENDERDRAGON = register("magicmadebymutantenderdragon", Builder.m_20704_(MagicbymutantenderdragonEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MagicbymutantenderdragonEntity::new).m_20699_(0.6F, 1.8F));
      MEDDS = register("projectile_medds", Builder.m_20704_(MeddsEntity::new, MobCategory.MISC).setCustomClientFactory(MeddsEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      MUTANTSTRAY = register("mutantstray", Builder.m_20704_(MutantstrayEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantstrayEntity::new).m_20719_().m_20699_(0.6F, 3.0F));
      MSB = register("projectile_msb", Builder.m_20704_(MsbEntity::new, MobCategory.MISC).setCustomClientFactory(MsbEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      MSBU = register("projectile_msbu", Builder.m_20704_(MsbuEntity::new, MobCategory.MISC).setCustomClientFactory(MsbuEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      MUTANT_NETHERITE_GOLEM = register("mutant_netherite_golem", Builder.m_20704_(MutantNetheriteGolemEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantNetheriteGolemEntity::new).m_20719_().m_20699_(2.0F, 6.0F));
      MNGW = register("projectile_mngw", Builder.m_20704_(MngwEntity::new, MobCategory.MISC).setCustomClientFactory(MngwEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      SLAM = register("projectile_slam", Builder.m_20704_(SlamEntity::new, MobCategory.MISC).setCustomClientFactory(SlamEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      MUTANT_SNIFFER = register("mutant_sniffer", Builder.m_20704_(MutantSnifferEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantSnifferEntity::new).m_20699_(1.2F, 1.8F));
      ANCIENT_TREE = register("ancient_tree", Builder.m_20704_(AncientTreeEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(AncientTreeEntity::new).m_20699_(0.6F, 1.8F));
      TRFH = register("projectile_trfh", Builder.m_20704_(TrfhEntity::new, MobCategory.MISC).setCustomClientFactory(TrfhEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      MUTANT_GHAST = register("mutant_ghast", Builder.m_20704_(MutantGhastEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantGhastEntity::new).m_20719_().m_20699_(2.3F, 4.0F));
      MGRI = register("projectile_mgri", Builder.m_20704_(MgriEntity::new, MobCategory.MISC).setCustomClientFactory(MgriEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      MMBMG = register("mmbmg", Builder.m_20704_(MmbmgEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(10000).setUpdateInterval(3).setCustomClientFactory(MmbmgEntity::new).m_20699_(0.6F, 1.8F));
      MGRI_2 = register("projectile_mgri_2", Builder.m_20704_(Mgri2Entity::new, MobCategory.MISC).setCustomClientFactory(Mgri2Entity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      ALPHA_MUTANT_IRON_GOLEM = register("alpha_mutant_iron_golem", Builder.m_20704_(AlphaMutantIronGolemEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(AlphaMutantIronGolemEntity::new).m_20719_().m_20699_(2.3F, 12.0F));
      AMIRI = register("projectile_amiri", Builder.m_20704_(AmiriEntity::new, MobCategory.MISC).setCustomClientFactory(AmiriEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      TRYU = register("tryu", Builder.m_20704_(TryuEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(0).setUpdateInterval(3).setCustomClientFactory(TryuEntity::new).m_20699_(0.6F, 1.8F));
      LK = register("projectile_lk", Builder.m_20704_(LkEntity::new, MobCategory.MISC).setCustomClientFactory(LkEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      THE_HANDOF_MUTANT_DROWNED = register("the_handof_mutant_drowned", Builder.m_20704_(TheHandofMutantDrownedEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(TheHandofMutantDrownedEntity::new).m_20719_().m_20699_(0.6F, 1.8F));
      HJ = register("projectile_hj", Builder.m_20704_(HjEntity::new, MobCategory.MISC).setCustomClientFactory(HjEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      SW = register("projectile_sw", Builder.m_20704_(SwEntity::new, MobCategory.MISC).setCustomClientFactory(SwEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      SW_2 = register("projectile_sw_2", Builder.m_20704_(Sw2Entity::new, MobCategory.MISC).setCustomClientFactory(Sw2Entity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      SW_1 = register("sw_1", Builder.m_20704_(Sw1Entity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(10000).setUpdateInterval(3).setCustomClientFactory(Sw1Entity::new).m_20699_(0.6F, 1.8F));
      SOUL = register("soul", Builder.m_20704_(SoulEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(SoulEntity::new).m_20719_().m_20699_(0.6F, 1.8F));
      SOUL_2 = register("soul_2", Builder.m_20704_(Soul2Entity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(Soul2Entity::new).m_20719_().m_20699_(0.6F, 1.8F));
      VG = register("projectile_vg", Builder.m_20704_(VgEntity::new, MobCategory.MISC).setCustomClientFactory(VgEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      GREAT_SWORD = register("great_sword", Builder.m_20704_(GreatSwordEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(GreatSwordEntity::new).m_20719_().m_20699_(2.0F, 30.0F));
      MUTANT_BOGGED = register("mutant_bogged", Builder.m_20704_(MutantBoggedEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantBoggedEntity::new).m_20719_().m_20699_(0.6F, 1.8F));
      THEHANDOFMUTANTBOGGED = register("thehandofmutantbogged", Builder.m_20704_(ThehandofmutantboggedEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(ThehandofmutantboggedEntity::new).m_20719_().m_20699_(0.6F, 1.8F));
      MBB = register("projectile_mbb", Builder.m_20704_(MbbEntity::new, MobCategory.MISC).setCustomClientFactory(MbbEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      IRON_GOLEM_HELICOPTER = register("iron_golem_helicopter", Builder.m_20704_(IronGolemHelicopterEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(IronGolemHelicopterEntity::new).m_20719_().m_20699_(1.0F, 1.8F));
      THE_GUARD_OF_MUTANT_BOGGED = register("the_guard_of_mutant_bogged", Builder.m_20704_(TheGuardOfMutantBoggedEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(TheGuardOfMutantBoggedEntity::new).m_20719_().m_20699_(0.6F, 1.8F));
      ROCKET = register("rocket", Builder.m_20704_(RocketEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(RocketEntity::new).m_20699_(1.0F, 0.6F));
      ROCKET_2 = register("projectile_rocket_2", Builder.m_20704_(Rocket2Entity::new, MobCategory.MISC).setCustomClientFactory(Rocket2Entity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      ROCKET_3 = register("rocket_3", Builder.m_20704_(Rocket3Entity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(Rocket3Entity::new).m_20699_(0.6F, 1.8F));
      WEAPONOFMUTANTWARDEN = register("weaponofmutantwarden", Builder.m_20704_(WeaponofmutantwardenEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(WeaponofmutantwardenEntity::new).m_20719_().m_20699_(0.6F, 7.0F));
      WOMW = register("projectile_womw", Builder.m_20704_(WomwEntity::new, MobCategory.MISC).setCustomClientFactory(WomwEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).m_20699_(0.5F, 0.5F));
      PUPPETOFMUTANTWARDEN = register("puppetofmutantwarden", Builder.m_20704_(PuppetofmutantwardenEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(PuppetofmutantwardenEntity::new).m_20719_().m_20699_(2.0F, 10.0F));
      SMOMW = register("smomw", Builder.m_20704_(SmomwEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(SmomwEntity::new).m_20719_().m_20699_(0.6F, 10.0F));
      BOAT = register("boat", Builder.m_20704_(BoatEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(BoatEntity::new).m_20719_().m_20699_(1.0F, 2.0F));
      MUTANT_PIGLIN_BRUTE = register("mutant_piglin_brute", Builder.m_20704_(MutantPiglinBruteEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MutantPiglinBruteEntity::new).m_20719_().m_20699_(1.0F, 5.0F));
      HANDOFMUTANTWITHER = register("handofmutantwither", Builder.m_20704_(HandofmutantwitherEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(HandofmutantwitherEntity::new).m_20719_().m_20699_(0.6F, 1.8F));
      BLACK_HOLE = register("black_hole", Builder.m_20704_(BlackHoleEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(BlackHoleEntity::new).m_20719_().m_20699_(0.6F, 50.0F));
      HEADOFMUTANTWITHER = register("headofmutantwither", Builder.m_20704_(HeadofmutantwitherEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(HeadofmutantwitherEntity::new).m_20719_().m_20699_(0.6F, 1.8F));
      TOWEROFMUTANTWITHER = register("towerofmutantwither", Builder.m_20704_(TowerofmutantwitherEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(TowerofmutantwitherEntity::new).m_20719_().m_20699_(0.6F, 1.8F));
      TOWEROFMUTANTWITHER_2 = register("towerofmutantwither_2", Builder.m_20704_(Towerofmutantwither2Entity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(Towerofmutantwither2Entity::new).m_20719_().m_20699_(0.6F, 1.8F));
      THETRUEESSENCE = register("thetrueessence", Builder.m_20704_(ThetrueessenceEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(ThetrueessenceEntity::new).m_20719_().m_20699_(0.6F, 1.8F));
      THE_QUEEN_MUTANT = register("the_queen_mutant", Builder.m_20704_(TheQueenMutantEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(TheQueenMutantEntity::new).m_20719_().m_20699_(1.5F, 35.0F));
      PB = register("pb", Builder.m_20704_(PBEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(PBEntity::new).m_20719_().m_20699_(0.6F, 55.0F));
   }
}
