org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.88
mod_id=ad_astra
mod_name=Ad Astra
mod_license=Terrarium License
mod_version=1.15.21-26.2-port
mod_group_id=earth.terrarium.adastra
