modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="themutantmobsmod"
version="1.1.1"
displayName="TheMutantMobsMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="megagatus"
description="The Mutant Mobs Mod"

[[dependencies.themutantmobsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.themutantmobsmod]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

